[package]
name = "moto"
version = "0.1.1"
edition = "2021"
description = "Bare-metal Rust firmware for ESP32-C5 (RISC-V RV32IMAC), simulated in Renode"

[dependencies]
riscv = "0.12"
riscv-rt = "0.13"
panic-halt = "1.0"

[profile.release]
opt-level = "s"
debug = 2
lto = true
